config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'cards/new'
  get 'card/show'
  get 'users/show'
  get 'users/logout'
  
  root to: 'tops#index'


  resources :tops do
    collection do
      get 'category_children' 
      get 'category_grandchildren'
    end
    resources :comments, only: [:create, :destroy]
  end
  post 'tops/:id' => 'tops#update'
  resources :categories,only: :index
  resources :users, only: :new

  resources :purchases

  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
    end
  end

  resources :products do
    resources :purchases, only: [:index] do
      collection do
        get 'done', to: 'purchases#done'
        post 'pay', to: 'purchases#pay'
      end
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true

  validates :first_name, presence: true ,format: { with: /\A[一-龥ぁ-ん]/}
  validates :last_name, presence: true ,format: { with: /\A[一-龥ぁ-ん]/ }
  validates :first_name_kana, presence: true ,format: { with: /\A[ァ-ヶー－]+\z/}
  validates :last_name_kana, presence: true ,format: { with: /\A[ァ-ヶー－]+\z/}
  validates :postal_code, presence: true
  validates :prefectures, presence: true
  validates :municipality, presence: true
  validates :house_number, presence: true
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :user 
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product 
  mount_uploader :image, ImageUploader


end

app/models/like.rb
class Like < ApplicationRecord
   belongs_to :user
   belongs_to :product, counter_cache: :likes_count

   validates :user_id, presence: true
   validates :product_id, presence: true
   validates_uniqueness_of :product_id, scope: :user_id
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :shipping

 belongs_to :user
#  belongs_to :category
#  belongs_to :brand
 has_many   :comments
 has_one    :address
 has_many   :likes
 has_many   :images, dependent: :destroy
 accepts_nested_attributes_for :images, allow_destroy: true

#  validates :name, :description, :price, :status, :sending,  presence: true
end

app/models/shipping.rb
class Shipping < ActiveHash::Base
  self.data = [
      {id: 1, name: '簡単フリマパック(日本郵便)'}, {id: 2, name: '簡単フリマパック(ヤマト運輸)'},
      {id: 3, name: 'レターパックライト'},{id: 4, name: 'レターパックプラス'},{id: 5, name: 'クリックポスト'},
      {id: 6, name: '宅急便コンパクト'},{id: 7, name: 'ゆうパック元払い'},{id: 8, name: 'ヤマト宅急便'},
      {id: 9, name: 'ゆうパケット'},{id: 10, name: 'ゆうメール元払い'},{id: 11, name: 'スマートレター'},
      {id: 12, name: '普通郵便'},{id: 13, name: 'ヤマト便'}
  ]
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable , :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
validates :nickname, presence: true
validates :first_name, presence: true ,format: { with: /\A[一-龥ぁ-ん]/}
validates :last_name, presence: true ,format: { with: /\A[一-龥ぁ-ん]/ }
validates :first_name_kana, presence: true ,format: { with: /\A[ァ-ヶー－]+\z/}
validates :last_name_kana, presence: true ,format: { with: /\A[ァ-ヶー－]+\z/}
validates :birthday_year, presence: true
validates :birthday_manth, presence: true
validates :birthday_day, presence: true

has_many :sns_credentials
has_one  :card
has_many :likes
has_many :products
has_many :comments
has_one  :address, dependent: :destroy
accepts_nested_attributes_for :address

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = sns.user || User.where(email: auth.info.email,).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  before_action :set_product, except: [:index, :new, :create, :category_children, :category_grandchildren]

  def index
    @products = Product.all.limit(3).order("id DESC")
  end
  
  def new
    @product = Product.new
    @product.images.new
    @category = Category.where(ancestry:nil)
  end

  def category_children
    @category_children = Category.find(params[:productcategory]).children 
  end

 
  def category_grandchildren
    @category_grandchildren = Category.find(params[:productcategory]).children
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
    else
      redirect_to new_top_path
    end
  end
  
  def show
    @product.images
    
    @comment = Comment.new
    @comments = @product.comments.includes(:user)
    @category = Category.where(ancestry:nil)

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    if @product.update(product_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @product.user_id == current_user.id && @product.destroy
      redirect_to root_path
    else
      render :edit
    end
  end


  private
  def product_params
    params.require(:product).permit(:name, :price, :status, :description, :sending,
                                    :send_cost, :user_id, :categories_id, :brands_id,
                                    :exhibition_status,:purchaser_id, :shippings_id,
                                    images_attributes: [:image, :_destroy, :id]).merge(user_id:current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end


  private

  def image_params
    params.require(:image).permit(:image)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tops/_exhibition.html.haml
-if current_user
  = link_to new_top_path do
    .exhibition
      %span.exhibition__text 出品する
      = image_tag "top/camera.png"

app/views/tops/_fifth_content.html.haml
.fifth
  .fifth__category-head
    ピックアップカテゴリー
  .fifth__category-title
    新規投稿商品
  .fifth__category-box
    =render "products-list"

app/views/tops/_first_content.html.haml
.first
  .first__title 人生を変えるフリマアプリ
  .first__message
    .first__message__up FURIMAはだれでもかんたんに出品・購入できる
    .first__message__row フリマアプリです
  .first__box
    = link_to image_tag(src= "top/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class: ".first__box__left"),"#"
    = link_to image_tag(src= "top/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class: ".first__box__right"),"#"

app/views/tops/_footer.html.haml
.footer
  .footer__contents
    .footer__contents__left
      %ul
        %li<
          .footer__contents__left__title FRIMAについて
          %ul
            %li<
              = link_to '会社概要(運営会社)', "#", class: ".header__contents__nav__left__category__first"
            %li<
              = link_to 'プライバシーポリシー', "#", class: ".header__contents__nav__left__category__second"
            %li<
              = link_to 'FURIMA利用規約', "#", class: ".header__contents__nav__left__category__third"
            %li<
              = link_to 'ポイントに関する特約', "#", class: ".header__contents__nav__left__category__fourth"
    .footer__contents__center
      %ul
        %li<
          .footer__contents__center__title FRIMAを見る
          %ul
            %li<
              .footer__contents__center__title__link
              = link_to 'カテゴリー一覧', "#", class: ".header__contents__nav__left__category__first"
            %li<
              .footer__contents__center__title__link
              = link_to 'ブランド一覧', "#", class: ".header__contents__nav__left__category__second"
    .footer__contents__right
      %ul
        %li<
          .footer__contents__right__title ヘルプ＆ガイド
          %ul
            %li<
              = link_to 'FURIMAガイド', "#", class: ".header__contents__nav__left__category__first"
            %li<
              = link_to 'FURIMAロゴ利用ガイドライン', "#", class: ".header__contents__nav__left__category__second"
            %li<
              = link_to 'お知らせ', "#", class: ".header__contents__nav__left__category__third"
  .footer__logo
    = link_to image_tag(src= "footer/logo-white.png", class: ".header__contents__main__logo",height:"45px",width:"auto"),root_path
  .footer__copyright 
    %p ©️ FURIMA

app/views/tops/_fourth_content.html.haml
.fourth
  .fourth__top
    FURIMAの特徴
  .fourth__main
    .fourth__main__item
      .fourth__main__item__img
        = image_tag src="second/icon-01-7furima.svg", size:"161x249"
      .fourth__main__item__subtitle
        簡単に売り買いできる
      .fourth__main__item__detail
        スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
    .fourth__main__item
      .fourth__main__item__img
        = image_tag src="second/icon-03-9furima.svg", size:"161x249"
      .fourth__main__item__subtitle
        売上金は即日振り込みに対応
      .fourth__main__item__detail
        午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
    .fourth__main__item
      .fourth__main__item__img
        = image_tag src="second/icon-04-cfurima.svg", size:"161x249"
      .fourth__main__item__subtitle
        様々な支払いに対応
      .fourth__main__item__detail
        お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

app/views/tops/_header.html.haml
.header
  .header__contents
    .header__contents__main
      = link_to image_tag(src= "header/logo.svg", class: ".header__contents__main__logo"),root_path
      = form_with(url: "#", local: true, method: :get, class: ".header__contents__main__form") do |form|
        = form.text_field :keyword, placeholder: "キーワードから探す", class: ".header__contents__main__form__text"
        = button_tag type: 'submit', class: "follow-btn" do
          = icon('fas', 'search')
    .header__contents__nav
      .header__contents__nav__left
        = link_to 'カテゴリー', "#", class: ".header__contents__nav__left__category"
        = link_to 'ブランド', "#", class: ".header__contents__nav__left__brand"
      .header__contents__nav__right
        - if user_signed_in?
          = link_to 'マイページ', users_show_path, class: ".header__contents__nav__right__mypage"
          = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: ".header__contents__nav__right__logOut"
        - else
          = link_to 'ログイン', new_user_session_path, class: ".header__contents__nav__right__logIn"
          = link_to '新規会員登録', new_user_path, class: ".header__contents__nav__right__signUp"

app/views/tops/_products-list.html.haml
- @products.each do |product|
  .fifth__category-box__list
    = link_to top_path(product.id) do
      .fifth__category-box__list__img{ style: "background-image: url(#{product.images.first.image});"}
        -if product.purchaser_id.present? 
          .fifth__category-box__list__img__sold
            .fifth__category-box__list__img__sold__inner SOLD
      .fifth__category-box__list__body
        .fifth__categiry-box__list__body__name
          = product.name
        .fifth__category-box__list__body__detail
          = product.price
          %span 円
          .fifth__category-box__list__body__detail__tax
            (税込)

app/views/tops/_second_content.html.haml
.second
  .second__title FURIMAが選ばれる3つの理由
  .second__box
    .second__box__left
      = image_tag "top/pict-reason-01-77b860b45f32923029756050dafc0f6df01a36675414b0f26f127c64a53baaea.jpg",width:"100%", alt:"image1", class:".second__box__left__image"
      .second__box__left__image__number 1
      .second__box__left__text
        %span>3分  
        &nbsp;ですぐに出品
      .second__box__left__about スマホで入力するだけで簡単に出品できる！
    .second__box__center
      = image_tag "top/pict-reason-02-3471b96ea7b52654510992e57dc05af07926de0836200059b7fa4ead05ee4d56.jpg",width:"100%", alt:"image1", class:".second__box__center__image"
      .second__box__center__image__number 2
      .second__box__center__text
        %span>シンプル
        &nbsp;で使いやすい
      .second__box__center__about めんどくさい入力は必要なく、検索も購入もスムーズ！
    .second__box__right
      = image_tag "top/pict-reason-03-1e3c743f3ba3db8c43987d2e257916a615aa8fc59c02bbc116f041a5580ec28f.jpg",width:"100%", alt:"image1", class:".second__box__right__image"
      .second__box__right__image__number 3
      .second__box__right__text
        %span>手数料
        &nbsp;業界最安
      .second__box__right__about 最大3%でお得に出品&購入！

  

app/views/tops/_sixth_content.html.haml
.sixth
  .sixth__body
    .sixth__body__title
      だれでもかんたん、人生を変えるフリマアプリ
    .sixth__body__text
      今すぐ無料ダウンロード
    .sixth__body__icon
      = link_to image_tag(src=  "second/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class: "sixth__body__icon__left"),"#"
      = link_to image_tag(src= "second/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class: "sixth__body__icon__right"),"#"

app/views/tops/_third_content.html.haml
.third
  .third__title 会員数日本一位
  .third__message
    .third__message__up FURIMAは、フリマアプリで最も人気。
    .third__message__middle 出品・購入回数も業界最多です！
    .third__message__row ほしかったあの商品に出会えるかもしれません。
  .third__box
    = link_to image_tag(src= "top/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class: ".first__box__left"),"#"
    = link_to image_tag(src= "top/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class: ".first__box__right"),"#"

app/views/tops/edit.html.haml
.main
  = form_for @product, url: top_path, method: :post do |f|
    #image-box
      #previews
        - if @product.persisted?
          - @product.images.each_with_index do |image, i|
            = image_tag image.image.url, data: { index: i }, width: "230", height: '230'
      = f.fields_for :images do |image|
        .file_groups
          .js-file_group{"data-index" => "#{image.index}"}
            = image.label :image, class: 'img_upload' do
              %span 画像を選択
              = image.file_field :image, class: 'js-file'
              %br/
            %span.js-remove 削除
          - if @product.persisted?
            = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
          - if @product.persisted?
            .js-file_group{"data-index" => "#{@product.images.count}"}
              = image.label :image, for: "product_images_attributes_#{@product.images.count}_image", class: 'img_upload' do
                %span 画像を選択
                = file_field_tag :image, name: "product[images_attributes][#{@product.images.count}][image]", class: 'js-file', id:"product_images_attributes_#{@product.images.count}_image"
                %br/
              %span.js-remove 削除

    .main__form
      .main__form__name
        .main__form__name__logo
          .main__form__name__logo__fix
            商品名
          .main__form__name__logo__must
            *必須
        .main__form__name__text
          = f.text_field :name, placeholder: "40文字まで"

      .main__form__description
        .main__form__description__logo
          .main__form__description__logo__fix
            商品説明
          .main__form__description__logo__must
            *必須
        .main__form__description__text
          = f.text_area :description, placeholder:"色・素材・重さ・低下・注意点などを記載しましょう（１０００文字まで）例：先月に５４００円で購入したセーターです。着用回数は５回未満です。素材はカシミヤなので着心地がいいです。", size: "67x13"

      .main__form__category
        .main__form__category__logo
          .main__form__category__logo__fix
            カテゴリー
          .main__form__category__logo__must
            *必須
        .main__form__category__text
          -# = f.collection_select :categories_id, @category, :id, :name, { prompt: "---" }, { class: "category_select-box", id: "category_select" }
          .main__form__category__text__children
          .main__form__category__text__grandchildren

      .main__form__brand
        .main__form__brand__logo
          .main__form__brand__logo__fix
            ブランド
          
        .main__form__brand__text
          = f.text_field :brands_id, placeholder: "指定なし" 
      .main__form__status
        .main__form__status__logo
          .main__form__status__logo__fix
            商品の状態
          .main__form__status__logo__must
            *必須
        .main__form__status__text
        .main__form__status__text
          = f.select :status, {新品: 1, 良: 2, 可: 3}



      .main__form__sendcost
        .main__form__sendcost__logo
          .main__form__sendcost__logo__fix
            配送料の負担
          .main__form__sendcost__logo__must
            *必須
        .main__form__sendcost__text
          = f.select :send_cost, {送料込み（出品者が負担）: 1, 送料別（購入者が負担）: 2}
      .main__form__sending
        .main__form__sending__logo
          .main__form__sending__logo__fix
            配送方法
        .main__form__sending__text
          = f.collection_select :shippings_id, Shipping.all, :id, :name
      .main__form__date
        .main__form__date__logo
          .main__form__date__logo__fix
            発送日の目安
          .main__form__date__logo__must
            *必須
        .main__form__date__text
          = f.text_field :sending, placeholder: "支払い後、１〜２日目安で発送" 
      .main__form__price
        .main__form__price__logo
          .main__form__price__logo__fix
            商品価格
          .main__form__price__logo__must
            *必須
        .main__form__price__text
          = f.number_field :price
      .main__form__btn
        = f.submit "更新する"
      -# %p= f.hidden_field :exhibition_status, {:value => "1"}
      %p
        = f.hidden_field :exhibition_status, :value => 1

app/views/tops/index.html.haml
.wrapper
  = render "first_content"
  = render "second_content"
  = render "third_content"
  = render "fourth_content"
  = render "fifth_content"
  = render "sixth_content"
  = render "exhibition"

app/views/tops/new.html.haml
.main
  = form_for @product, url: tops_path, method: :post do |f|
    #image-box
      #previews
        - if @product.persisted?
          - @product.images.each_with_index do |image, i|
            = image_tag image.image.url, data: { index: i }, width: "100", height: '100'
      = f.fields_for :images do |image|
        .file_groups
          .js-file_group{"data-index" => "#{image.index}"}
            = image.label :image, class: 'img_upload' do
              %span 画像を選択
              = image.file_field :image, class: 'js-file'
              %br/
            %span.js-remove 削除
          - if @product.persisted?
            = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
      - if @product.persisted?
        .js-file_group{"data-index" => "#{@product.images.count}"}
          = file_field_tag :image, name: "product[images_attributes][#{@product.images.count}][image]", class: 'js-file'
          .js-remove 削除

    .main__form
      .main__form__name
        .main__form__name__logo
          .main__form__name__logo__fix
            商品名
          .main__form__name__logo__must
            *必須
        .main__form__name__text
          = f.text_field :name, placeholder: "40文字まで"

      .main__form__description
        .main__form__description__logo
          .main__form__description__logo__fix
            商品説明
          .main__form__description__logo__must
            *必須
        .main__form__description__text
          = f.text_area :description, placeholder:"色・素材・重さ・低下・注意点などを記載しましょう（１０００文字まで）例：先月に５４００円で購入したセーターです。着用回数は５回未満です。素材はカシミヤなので着心地がいいです。", size: "67x13"

      .main__form__category
        .main__form__category__logo
          .main__form__category__logo__fix
            カテゴリー
          .main__form__category__logo__must
            *必須
        .main__form__category__text
          = f.collection_select :categories_id, @category, :id, :name, { prompt: "---" }, { class: "category_select-box", id: "category_select" }
          .main__form__category__text__children
          .main__form__category__text__grandchildren

      .main__form__brand
        .main__form__brand__logo
          .main__form__brand__logo__fix
            ブランド
          
        .main__form__brand__text
          = f.text_field :brands_id, placeholder: "指定なし" 
      .main__form__status
        .main__form__status__logo
          .main__form__status__logo__fix
            商品の状態
          .main__form__status__logo__must
            *必須
        .main__form__status__text
        .main__form__status__text
          = f.select :status, {新品: 1, 良: 2, 可: 3}



      .main__form__sendcost
        .main__form__sendcost__logo
          .main__form__sendcost__logo__fix
            配送料の負担
          .main__form__sendcost__logo__must
            *必須
        .main__form__sendcost__text
          = f.select :send_cost, {送料込み（出品者が負担）: 1, 送料別（購入者が負担）: 2}
      .main__form__sending
        .main__form__sending__logo
          .main__form__sending__logo__fix
            配送方法
        .main__form__sending__text
          = f.collection_select :shippings_id, Shipping.all, :id, :name
      .main__form__date
        .main__form__date__logo
          .main__form__date__logo__fix
            発送日の目安
          .main__form__date__logo__must
            *必須
        .main__form__date__text
          = f.text_field :sending, placeholder: "支払い後、１〜２日目安で発送" 
      .main__form__price
        .main__form__price__logo
          .main__form__price__logo__fix
            商品価格
          .main__form__price__logo__must
            *必須
        .main__form__price__text
          = f.number_field :price
      .main__form__btn
        = f.submit "出品する"
      -# %p= f.hidden_field :exhibition_status, {:value => "1"}
      %p
        = f.hidden_field :exhibition_status, :value => 1

app/views/tops/show.html.haml
%section.showMain
  .showMain__content
    .topContent
      .itemBox
        .itemBox__name 
          =@product.name
        .itemBox__image
          .itemBox__image__main{style:"background-image: url(#{@product.images.first.image});"}
          .itemBox__image__sub
            - @product.images.each do |image|
              %li{style:"background-image: url(#{image.image});"}
          
            
        .itemBox__price
          .itemBox__price--num 
            =@product.price
          .itemBox__price--detail
            %span (税込)
            %span 送料込み
        .product-btn

          - if user_signed_in? && current_user.id == @product.user_id
            .product-edit-button
              = link_to "商品情報を編集する",  edit_top_path(@product)
            .product-del-button
              = link_to 'この商品を削除する', top_path(@product), method: :delete, data: { confirm: "本当に削除しますか？" }
          - elsif @product.purchaser_id == 1
            .soldout-notification
              売り切れです
          - else
            .product-buy-button
              %button.decisionBtn{name: 'button', type: 'submit'}
                = link_to "購入画面に進む", product_purchases_path(@product)

        .itemDetail 
          =@product.description
        .table
          %table
            %tr 
              %th 出品者
              %td 
                = @product.user.nickname
            %tr

              %th カテゴリー
              %td
                = render "categories/show"
            
            %tr
            -#あとで使用するかも
              -# %th ブランド
              -# %td
              -#   =@product.brand.brand_name
            %tr
              %th 商品の状態
              %td 
                =@product.status
                %tn (1.新品　2.良　３.可)
                  
            %tr
              %th 配送料の負担
              %td 
                =@product.send_cost
                %tn (1.送料込み（出品者が負担）2.送料別（購入者が負担）)
            %tr
              %th 発送日の目安
              %td
                =@product.sending
            %tr
              %th 配送方法
              %td 
                =@product.shippings_id
      .optionalArea
        %ul
          %li#likeBtn.optionalBtn.likeBtn
            %i.fas.fa-star
            お気に入り
        %ul
          %li.optional
            = link_to '#' do
              %i.fa.fa-flag
              不適切な商品の通報
      .commentBox
        .commentBox__comment
          %h2 コメント一覧
          -if @product.comments
            - @product.comments.each do |comment|
              .comment-user
                = comment.user.nickname
              .comment-text
                = comment.comment
                .comment-date
                  %i.far.fa-clock
                  = comment.created_at.strftime("%Y/%m/%d %H:%M")
                -if current_user
                  - if user_signed_in? && current_user.id == comment.user_id
                    = link_to top_comment_path(comment.product.id, comment.id),class: "comment-destroy", method: :delete, data: { turbolinks: false} do
                      %i.fas.fa-trash-alt
        
        %p.noticeMsg
          相手のことを考え丁寧なコメントを心がけましょう。
          %br
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
       
        .container
        - if current_user
          = form_with(model: [@product, @comment],url:top_comments_path(@product), method: :post, local: true,) do |form|
            = form.text_area :comment, placeholder: "コメントする",size: "70x4"
            = form.submit 'コメントする', class: "btn"
        - else
          %strong
            %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※

    %ul.links
      %li
        = link_to '#' do
          %i.fa.fa-angle-left
          前の商品
      %li
        = link_to '#' do
          後ろの商品
          %i.fa.fa-angle-right
    .relatedItems
      = link_to 'レディースをもっと見る', '#'