config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'cards/new'
  get 'card/show'
  get 'users/show'
  get 'users/logout'
  
  root to: 'tops#index'


  resources :tops do
    collection do
      get 'category_children' 
      get 'category_grandchildren'
    end
    resources :comments, only: [:create, :destroy]
  end
  post 'tops/:id' => 'tops#update'
  resources :categories,only: :index
  resources :users, only: :new

  resources :purchases

  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
    end
  end

  resources :products do
    resources :purchases, only: [:index] do
      collection do
        get 'done', to: 'purchases#done'
        post 'pay', to: 'purchases#pay'
      end
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true

  validates :first_name, presence: true ,format: { with: /\A[一-龥ぁ-ん]/}
  validates :last_name, presence: true ,format: { with: /\A[一-龥ぁ-ん]/ }
  validates :first_name_kana, presence: true ,format: { with: /\A[ァ-ヶー－]+\z/}
  validates :last_name_kana, presence: true ,format: { with: /\A[ァ-ヶー－]+\z/}
  validates :postal_code, presence: true
  validates :prefectures, presence: true
  validates :municipality, presence: true
  validates :house_number, presence: true
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :user 
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product 
  mount_uploader :image, ImageUploader


end

app/models/like.rb
class Like < ApplicationRecord
   belongs_to :user
   belongs_to :product, counter_cache: :likes_count

   validates :user_id, presence: true
   validates :product_id, presence: true
   validates_uniqueness_of :product_id, scope: :user_id
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :shipping

 belongs_to :user
#  belongs_to :category
#  belongs_to :brand
 has_many   :comments
 has_one    :address
 has_many   :likes
 has_many   :images, dependent: :destroy
 accepts_nested_attributes_for :images, allow_destroy: true

#  validates :name, :description, :price, :status, :sending,  presence: true
end

app/models/shipping.rb
class Shipping < ActiveHash::Base
  self.data = [
      {id: 1, name: '簡単フリマパック(日本郵便)'}, {id: 2, name: '簡単フリマパック(ヤマト運輸)'},
      {id: 3, name: 'レターパックライト'},{id: 4, name: 'レターパックプラス'},{id: 5, name: 'クリックポスト'},
      {id: 6, name: '宅急便コンパクト'},{id: 7, name: 'ゆうパック元払い'},{id: 8, name: 'ヤマト宅急便'},
      {id: 9, name: 'ゆうパケット'},{id: 10, name: 'ゆうメール元払い'},{id: 11, name: 'スマートレター'},
      {id: 12, name: '普通郵便'},{id: 13, name: 'ヤマト便'}
  ]
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable , :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
validates :nickname, presence: true
validates :first_name, presence: true ,format: { with: /\A[一-龥ぁ-ん]/}
validates :last_name, presence: true ,format: { with: /\A[一-龥ぁ-ん]/ }
validates :first_name_kana, presence: true ,format: { with: /\A[ァ-ヶー－]+\z/}
validates :last_name_kana, presence: true ,format: { with: /\A[ァ-ヶー－]+\z/}
validates :birthday_year, presence: true
validates :birthday_manth, presence: true
validates :birthday_day, presence: true

has_many :sns_credentials
has_one  :card
has_many :likes
has_many :products
has_many :comments
has_one  :address, dependent: :destroy
accepts_nested_attributes_for :address

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = sns.user || User.where(email: auth.info.email,).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  require 'payjp'
  before_action :set_card, :set_product

  def new
    @user = User.new
  end

  def index
    if @card.blank?
      redirect_to new_card_path
    else
      Payjp.api_key = Rails.application.credentials[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id) 
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def pay
    Payjp.api_key = Rails.application.credentials[:PAYJP_PRIVATE_KEY]
    Payjp::Charge.create(
      :amount => @product.price,
      :customer => @card.customer_id,
      :currency => 'jpy',
    )
    redirect_to done_product_purchases_path
  end


  def create
    User.create(user_params)
  end


  def  done
    @product_purchaser = Product.find(params[:product_id])
    @product_purchaser.update( purchaser_id: current_user.id)
  end

  private
  def user_params
    params.require(:user).permit(:first_name)
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:product_id])
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/purchases/done.html.haml
.purchased__confirmation__messagebox
  %h1.purchased__confirmation__messagebox__attention
    %i.far.fa-clock
      発送をお待ちください
    %h2.purchased__confirmation__messagebox__title
      購入が完了しました
    .buy__content__item
      .buy__content__item__inner
        .buy__content__item__inner__main
          .buy__content__item__inner__main__image{style:"background-image: url(#{@product.images.first.image});"}
          .buy__content__item__inner__main__detail
            .buy__content__item__inner__main__detail__name
              = @product.name
              %p.buy__content__item__inner__main__detail__name--price
                %span 
                  = "¥#{@product.price.to_s}"
                %span
                  .buy__content__item__inner__main__detail__name--shipping-fee (税込) 送料込み
          .buy__content__item__inner__lower
            %form.buy__content__item__inner__lower__form
              .buy__content__item__inner__lower__form__table
                .buy__content__item__inner__lower__form__table--left
                  支払金額
                .buy__content__item__inner__lower__form__table--right
                  = "¥#{@product.price.to_s}"
              .buy__content__item__inner__lower__form__submit
                = link_to "トップページへ戻る", root_path, class: 'buy-content__user-info__submit__button'

app/views/purchases/edit.html.haml
テスト

app/views/purchases/index.html.haml
%section.buyMain
  .buyMain__content
    .topContent
      %ul.productInfo
        %li.productImg
          = image_tag 'top/birdCute.jpeg', alt: 'BirdCute', class: 'itemBox__image__main1'
          %ul.productInfo__detail
            %li.productInfo__detail__name
              = @product.name
            %li.productInfo__detail__price
              = @product.price
            %li.productInfo__detail__sendCost
              %span
                %i.fas.fa-truck-moving
                送料込み｜出品者負担
      .payInfo
        .row 支払い方法
        -# 競合起きるか実験
        .table
          %table
            %tr
              %th フリマポイント
              %td 
                10ポイント
                %br
                保有ポイント：50
            %tr
              %th 支払い方法
              %td クレジットカード
        .paymentInfo
          .row2
            .col1 商品金額
            .col1_right
              = "#{@product.price.to_s}円"
          .row3
            .col2 決済手数料
            .col2_right 0円
          .row4
            .col3 支払金額
            .col3_right
              = "#{@product.price.to_s}円"
            -# .buy-price-table__right
            -#   = "¥#{@product.price.to_s}"
          .buy-content__user-info
            .buy-content__user-info__inner
              %h3 支払方法
              .user-info-update
                = link_to "変更する", "#", calss:"update-btn"
              .user-info-text
              - if @default_card_information.blank?
                %br /
              - else
                = "**** **** **** " + "#{@default_card_information.last4}"
                %br
                - exp_month = @default_card_information.exp_month.to_s
                - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                = "有効期限 " + exp_month + " / " + exp_year
                %br

      .sendingInfo
        .col4 配送先住所
        %ul.col5
          %li.addressPostalCode 〒 111-2222
          %li.address 埼玉県の真ん中らへん
          %li.addressName 加藤 陽 様
        .row  配送先情報
        %ul.col6
          %li.sendingInfoDetail 普通郵便
          %li.sendingCost
            %span
              %i.fas.fa-truck-moving
              送料込み｜出品者負担
          %li.sendingDay 発送までの目安：支払い確定後 2 ~ 3日後
      .formInfo
        = form_tag(action: :pay, method: :post) do
          %button.buy-button{type:"submit"} 購入する

app/views/purchases/new.html.haml
%section.buyMain
  .buyMain__content
    .topContent
      %ul.productInfo
        %li.productImg
          = image_tag 'top/birdCute.jpeg', alt: 'BirdCute', class: 'itemBox__image__main1'
          %ul.productInfo__detail
            %li.productInfo__detail__name カレーライス
            %li.productInfo__detail__price 3000円
            %li.productInfo__detail__sendCost
              %span
                %i.fas.fa-truck-moving
                送料込み｜出品者負担
      .payInfo
        .row 支払い方法
        -# 競合起きるか実験
        .table
          %table
            %tr
              %th フリマポイント
              %td 
                10ポイント
                %br
                保有ポイント：50
            %tr
              %th 支払い方法
              %td クレジットカード
        .paymentInfo
          .row2
            .col1 商品金額
            .col1_right ¥1,000
          .row3
            .col2 決済手数料
            .col2_right 0円
          .row4
            .col3 支払金額
            .col3_right ¥1,000
      -if user_signed_in?
        -if @product.users_id == current_user.id
          = link_to edit_purchase_path(@product) do
            .product-edit-btn 商品の編集
            .product-btn-or or
            .product-stop-btn 出品を一旦停止する
        -else 
          -if @product.status == 0
            = link_to product_card_confirmation_path(@product) do
              .product-buy-btn 購入画面に進む
          -else
            .product-buy-btn-sold 売り切れました
      -else
        -if @product.status == 0
          = link_to "/users/sign_in" do
            .product-buy-btn 購入画面に進む
        -else
          .product-buy-btn-sold 売り切れました

      .sendingInfo
        .col4 配送先住所
        %ul.col5
          %li.addressPostalCode 〒 111-2222
          %li.address 埼玉県の真ん中らへん
          %li.addressName 加藤 陽 様
        .row  配送先情報
        %ul.col6
          %li.sendingInfoDetail 普通郵便
          %li.sendingCost
            %span
              %i.fas.fa-truck-moving
              送料込み｜出品者負担
          %li.sendingDay 発送までの目安：支払い確定後 2 ~ 3日後
      .formInfo
        %form#buy_product.buy_product{"accept-charaset" => "UTF-8", action: "#", method: "post"}
          %button.decisionBtn{name: 'button', type: 'submit'}
            注文確定