config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'cards/new'
  get 'card/show'
  get 'users/show'
  get 'users/logout'
  
  root to: 'tops#index'


  resources :tops do
    collection do
      get 'category_children' 
      get 'category_grandchildren'
    end
    resources :comments, only: [:create, :destroy]
  end
  post 'tops/:id' => 'tops#update'
  resources :categories,only: :index
  resources :users, only: :new

  resources :purchases

  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
    end
  end

  resources :products do
    resources :purchases, only: [:index] do
      collection do
        get 'done', to: 'purchases#done'
        post 'pay', to: 'purchases#pay'
      end
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true

  validates :first_name, presence: true ,format: { with: /\A[一-龥ぁ-ん]/}
  validates :last_name, presence: true ,format: { with: /\A[一-龥ぁ-ん]/ }
  validates :first_name_kana, presence: true ,format: { with: /\A[ァ-ヶー－]+\z/}
  validates :last_name_kana, presence: true ,format: { with: /\A[ァ-ヶー－]+\z/}
  validates :postal_code, presence: true
  validates :prefectures, presence: true
  validates :municipality, presence: true
  validates :house_number, presence: true
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :user 
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product 
  mount_uploader :image, ImageUploader


end

app/models/like.rb
class Like < ApplicationRecord
   belongs_to :user
   belongs_to :product, counter_cache: :likes_count

   validates :user_id, presence: true
   validates :product_id, presence: true
   validates_uniqueness_of :product_id, scope: :user_id
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :shipping

 belongs_to :user
#  belongs_to :category
#  belongs_to :brand
 has_many   :comments
 has_one    :address
 has_many   :likes
 has_many   :images, dependent: :destroy
 accepts_nested_attributes_for :images, allow_destroy: true

#  validates :name, :description, :price, :status, :sending,  presence: true
end

app/models/shipping.rb
class Shipping < ActiveHash::Base
  self.data = [
      {id: 1, name: '簡単フリマパック(日本郵便)'}, {id: 2, name: '簡単フリマパック(ヤマト運輸)'},
      {id: 3, name: 'レターパックライト'},{id: 4, name: 'レターパックプラス'},{id: 5, name: 'クリックポスト'},
      {id: 6, name: '宅急便コンパクト'},{id: 7, name: 'ゆうパック元払い'},{id: 8, name: 'ヤマト宅急便'},
      {id: 9, name: 'ゆうパケット'},{id: 10, name: 'ゆうメール元払い'},{id: 11, name: 'スマートレター'},
      {id: 12, name: '普通郵便'},{id: 13, name: 'ヤマト便'}
  ]
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable , :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
validates :nickname, presence: true
validates :first_name, presence: true ,format: { with: /\A[一-龥ぁ-ん]/}
validates :last_name, presence: true ,format: { with: /\A[一-龥ぁ-ん]/ }
validates :first_name_kana, presence: true ,format: { with: /\A[ァ-ヶー－]+\z/}
validates :last_name_kana, presence: true ,format: { with: /\A[ァ-ヶー－]+\z/}
validates :birthday_year, presence: true
validates :birthday_manth, presence: true
validates :birthday_day, presence: true

has_many :sns_credentials
has_one  :card
has_many :likes
has_many :products
has_many :comments
has_one  :address, dependent: :destroy
accepts_nested_attributes_for :address

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = sns.user || User.where(email: auth.info.email,).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to cards_path(current_user.id) if card.exists?
  end


  def pay
    Payjp.api_key = Rails.application.credentials[:PAYJP_PRIVATE_KEY]
    if params['payjp-token'].blank?
      redirect_to new_card_path
    else
      customer = Payjp::Customer.create(
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to card_path(current_user.id)
      else
        redirect_to pay_cards_path
      end
    end
  end

  def destroy 
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to new_card_path
  end

  def show
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to new_card_path 
    else
      Payjp.api_key = Rails.application.credentials[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  before_action :set_product, except: [:index, :new, :create, :category_children, :category_grandchildren]

  def index
    @products = Product.all.limit(3).order("id DESC")
  end
  
  def new
    @product = Product.new
    @product.images.new
    @category = Category.where(ancestry:nil)
  end

  def category_children
    @category_children = Category.find(params[:productcategory]).children 
  end

 
  def category_grandchildren
    @category_grandchildren = Category.find(params[:productcategory]).children
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
    else
      redirect_to new_top_path
    end
  end
  
  def show
    @product.images
    
    @comment = Comment.new
    @comments = @product.comments.includes(:user)
    @category = Category.where(ancestry:nil)

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    if @product.update(product_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @product.user_id == current_user.id && @product.destroy
      redirect_to root_path
    else
      render :edit
    end
  end


  private
  def product_params
    params.require(:product).permit(:name, :price, :status, :description, :sending,
                                    :send_cost, :user_id, :categories_id, :brands_id,
                                    :exhibition_status,:purchaser_id, :shippings_id,
                                    images_attributes: [:image, :_destroy, :id]).merge(user_id:current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end


  private

  def image_params
    params.require(:image).permit(:image)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/card/new.html.haml
.mypagebox
  .mypagebox__leftcolumn
    .mypagebox__leftcolumn--mypage マイページ
    .mypagebox__leftcolumn--cardreg
      = link_to "カード登録/変更", 'card/new'
    .mypagebox__leftcolumn--logout
      = link_to "ログアウト", 'logout'

  .creditbox
    = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
      %label カード番号
      = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
      %br
      %label 有効期限
      %select#exp_month{name: "exp_month", type: "text"}
        %option{value: ""} --
        %option{value: "1"}01
        %option{value: "2"}02
        %option{value: "3"}03
        %option{value: "4"}04
        %option{value: "5"}05
        %option{value: "6"}06
        %option{value: "7"}07
        %option{value: "8"}08
        %option{value: "9"}09
        %option{value: "10"}10
        %option{value: "11"}11
        %option{value: "12"}12
      %span 月/
      %select#exp_year{name: "exp_year", type: "text"}
        %option{value: ""} --
        %option{value: "2020"}20
        %option{value: "2021"}21
        %option{value: "2022"}22
        %option{value: "2023"}23
        %option{value: "2024"}24
        %option{value: "2025"}25
        %option{value: "2026"}26
        %option{value: "2027"}27
        %option{value: "2028"}28
        %option{value: "2029"}29
      %span 年
      %br
      %label セキュリティコード
      = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
      #card_token
      = submit_tag "追加する", id: "token_submit"

app/views/cards/_mypageSidebar.html.haml
.mypagebox__leftcolumn
  .mypagebox__leftcolumn--mypage
    = link_to "マイページ", users_show_path
  .mypagebox__leftcolumn--cardreg
    = link_to "カード登録/変更", new_card_path
  .mypagebox__leftcolumn--logout
    = link_to "ログアウト", 'logout'

app/views/cards/new.html.haml
.mypagebox
  = render "mypageSidebar"

  .creditbox
    = form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
      %label カード番号
      .require 必須
      = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
      %ul.signup-card-list
        %li
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?238737266",width:"49px",height:"20px"
        %li
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?238737266",width:"34px",height:"20px"
        %li
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?238737266",width:"30px",height:"20px"
        %li
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?238737266",width:"32px",height:"20px"
        %li
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?238737266",width:"21px",height:"20px"
        %li
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?238737266",width:"32px",height:"20px"
        %li
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?238737266",width:"32px",height:"20px"
      %br
      %label 有効期限
      .require 必須
      %select#exp_month{name: "exp_month", type: "text"}
        %option{value: ""} --
        %option{value: "1"}01
        %option{value: "2"}02
        %option{value: "3"}03
        %option{value: "4"}04
        %option{value: "5"}05
        %option{value: "6"}06
        %option{value: "7"}07
        %option{value: "8"}08
        %option{value: "9"}09
        %option{value: "10"}10
        %option{value: "11"}11
        %option{value: "12"}12
      %span 月/
      %select#exp_year{name: "exp_year", type: "text"}
        %option{value: ""} --
        %option{value: "2019"}19
        %option{value: "2020"}20
        %option{value: "2021"}21
        %option{value: "2022"}22
        %option{value: "2023"}23
        %option{value: "2024"}24
        %option{value: "2025"}25
        %option{value: "2026"}26
        %option{value: "2027"}27
        %option{value: "2028"}28
        %option{value: "2029"}29
      %span 年
      %br
      %br
      %label セキュリティコード
      .require 必須
      = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
      %br
      #card_token
      %br
      = submit_tag "追加する", id: "token_submit"

app/views/cards/show.html.haml
.mypagebox
  = render "mypageSidebar"


  .form__content
    .form__title 登録済みクレジットカード
    %br
    = "**** **** **** " + @default_card_information.last4
    %br
    - exp_month = @default_card_information.exp_month.to_s
    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    = exp_month + " / " + exp_year
    = form_tag(card_path(current_user.id), method: :delete, id: 'charge-form',  name: "inputForm") do
      %input{ type: "hidden", name: "card_id", value: "" }
      %button.delete-btn 削除する